name: Workflow
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  Ubuntu:
    name: Add labels to issues
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: alexleventer/github-issue-due-dates-action@1.2.0
        with:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
      - name: name test
        run: |
          echo "test message"
          actions:
          - action: send email
            type: "EMAIL"
            title: "$title"
            content: "<b>this is a message test</b>"
             recipients: "carlos7981my@gmail.com"
