name: Main Workflow
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  Ubuntu:
    name: Add labels to issues
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: Gatubel/github-issue-due-dates-action@master
        with:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
