name: Main Workflow
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  Ubuntu:
    name: Add labels to issues
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: JoseBilbao/github-issue-due-dates-action@main
        with:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
          MJ_APIKEY_PRIVATE: "${{ secrets.MJ_APIKEY_PRIVATE }}"
          MJ_APIKEY_PUBLIC: "${{ secrets.MJ_APIKEY_PUBLIC }}"
      - name: name test
        run: |
          echo "test message"
    
